# coding: utf-8

# flake8: noqa

"""
    Triple Play Pay API

    Payment API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@tripleplaypay.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.api_api import ApiApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.response import Response
