# coding: utf-8

# flake8: noqa
"""
    Triple Play Pay API

    Payment API  # noqa: E501

    OpenAPI spec version: 1.0.1-oas3
    Contact: support@tripleplaypay.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.response import Response
