/*
 * Triple Play Pay API
 *
 * Payment API
 *
 * API version: 1.0.0
 * Contact: support@tripleplaypay.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Response struct {
	Status bool `json:"status,omitempty"`
	Id string `json:"id,omitempty"`
	Message *interface{} `json:"message,omitempty"`
	Meta *interface{} `json:"meta,omitempty"`
	Method string `json:"method,omitempty"`
}
