# coding: utf-8

"""
    Triple Play Pay API

    Payment API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@tripleplaypay.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "swagger-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Triple Play Pay API",
    author_email="support@tripleplaypay.com",
    url="",
    keywords=["Swagger", "Triple Play Pay API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    Payment API  # noqa: E501
    """
)
