<?php
/**
 * ApiApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Triple Play Pay API
 *
 * Payment API
 *
 * OpenAPI spec version: 1.0.1-oas3
 * Contact: support@tripleplaypay.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.33
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * ApiApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ApiApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for activate
     *
     * Setup new Credit Card Terminal..
     *
     */
    public function testActivate()
    {
    }

    /**
     * Test case for authorize
     *
     * Used to verify funds when the total amount of the purchase is unknown..
     *
     */
    public function testAuthorize()
    {
    }

    /**
     * Test case for charge
     *
     * Process payment or settle a previous charge. *card **bank.
     *
     */
    public function testCharge()
    {
    }

    /**
     * Test case for credit
     *
     * A Credit transaction is used to refund a cardholder for a previous transaction..
     *
     */
    public function testCredit()
    {
    }

    /**
     * Test case for enroll
     *
     * Enroll a new merchant or retrieve status of pending merchant..
     *
     */
    public function testEnroll()
    {
    }

    /**
     * Test case for report
     *
     * Get transaction detail history.
     *
     */
    public function testReport()
    {
    }

    /**
     * Test case for settle
     *
     * Alternative to sending a transactionId to charge, this method will settle an outstanding Authorization..
     *
     */
    public function testSettle()
    {
    }

    /**
     * Test case for tokenize
     *
     * Create a token for later use..
     *
     */
    public function testTokenize()
    {
    }

    /**
     * Test case for void
     *
     * A Void transaction can be used to back out a previous Sale transaction..
     *
     */
    public function testVoid()
    {
    }
}
