# coding: utf-8

"""
    Triple Play Pay API

    Payment API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@tripleplaypay.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.api_api import ApiApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self):
        self.api = ApiApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_authorize(self):
        """Test case for authorize

        Used to verify funds when the total amount of the purchase is unknown.  # noqa: E501
        """
        pass

    def test_charge(self):
        """Test case for charge

        Charge a credit card or settle a previous charge.  # noqa: E501
        """
        pass

    def test_credit(self):
        """Test case for credit

        A Credit transaction is used to refund a cardholder for a previous transaction.  # noqa: E501
        """
        pass

    def test_enroll(self):
        """Test case for enroll

        Enroll a new merchant or retrieve status of pending merchant.  # noqa: E501
        """
        pass

    def test_settle(self):
        """Test case for settle

        Alternative to sending a transactionId to charge, this method will settle an outstanding Authorization.  # noqa: E501
        """
        pass

    def test_tokenize(self):
        """Test case for tokenize

        Create a token for later use.  # noqa: E501
        """
        pass

    def test_void(self):
        """Test case for void

        A Void transaction can be used to back out a previous Sale transaction.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
